Controllers/ProductosController.cs
using Amazon.Models;
using Amazon.Models.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Amazon.Controllers
{
    public class ProductosController : Controller
    {
        private readonly IProductosRepository _productosRepository;
        private readonly ICarritoRepository _carritoRepository;
        public ProductosController(IProductosRepository productosRepository, ICarritoRepository carritoRepository)
        {
            _productosRepository = productosRepository;
            _carritoRepository = carritoRepository;
        }

        // GET: ProductosController
        public async Task<IActionResult> IndexAsync()
        {
            var productos = await _productosRepository.GetAll();
            return View(productos);
        }

        // GET: ProductosController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var producto = await _productosRepository.GetById(id);
            return View(producto);
        }

        // GET: ProductosController/Create
        public ActionResult Create()
        {
            if (!CheckSession("Admin"))
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        // POST: ProductosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Productos productos)
        {
            if (!CheckSession("Admin"))
            {
                return RedirectToAction("Index");
            }
            try
            {
                _productosRepository.Create(productos);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductosController/Edit/5
        public async Task<IActionResult> EditAsync(int id)
        {
            if (!CheckSession("Admin"))
            {
                return RedirectToAction("Index");
            }
            var producto = await _productosRepository.GetById(id);
            return producto == null ? NotFound() : View(producto);
        }

        // POST: ProductosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Productos productos)
        {
            if (!CheckSession("Admin"))
            {
                return RedirectToAction("Index");
            }
            if (ModelState.IsValid)
            {
                _productosRepository.Update(productos);
                return RedirectToAction("Index");
            }
            return View(productos);
        }

        // GET: ProductosController/Delete/5
        public async Task<IActionResult> DeleteAsync(int id)
        {
            if (!CheckSession("Admin"))
            {
                return RedirectToAction("Index");
            }
            var producto = await _productosRepository.GetById(id);
            return producto == null ? NotFound() : View(producto);
        }

        // POST: ProductosController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            if (!CheckSession("Admin")){
                return RedirectToAction("Index");
            }
            var producto = await _productosRepository.GetById(id);
            try
            {
                _productosRepository.Delete(id);
                return RedirectToAction("Index");
            } catch(InvalidOperationException ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return View("Delete", producto);
            }
        }
        // POST: AddToCart
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToCart(int productID)
        {
            int userID = Global.user.UsuarioID;
            await _carritoRepository.AddProducto(productID, userID);
            Global.carritoCantidad = await _carritoRepository.ProductosCarrito(Global.user.UsuarioID);
            return RedirectToAction("Index");
        }
        private bool CheckSession(string key)
        {
            return HttpContext.Session.Keys.Contains(key);
        }
    }
}

Controllers/VentaController.cs
using Amazon.Models;
using Amazon.Models.Repository;
using Microsoft.AspNetCore.Mvc;

namespace Amazon.Controllers
{
    public class VentaController : Controller
    {
        private readonly IVentaRepository _ventaRepository;

        public VentaController(IVentaRepository ventaRepository)
        {
            _ventaRepository = ventaRepository;
        }
        public async Task<ActionResult> Index()
        {
            if (!CheckSession("User"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (CheckSession("Admin"))
            {
                var ventas = await _ventaRepository.GetVentasAdmin();
                return View(ventas);
            } else
            {
                return RedirectToAction("Details");
            }
        }
        public async Task<IActionResult> Details(int? ventaID)
        {
            int venta = ventaID ?? await _ventaRepository.GetVentaID(Global.user.UsuarioID);
            var ventaDetalles = await _ventaRepository.GetDetallesVenta(venta);
            return View(ventaDetalles);
        }
        public async Task<IActionResult> Edit(int ventaID)
        {
            if (!CheckSession("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            var detallesVenta = await _ventaRepository.GetDetallesVenta(ventaID);
            return detallesVenta == null ? NotFound() : View(detallesVenta);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DetallesVenta detallesVenta)
        {
            try
            {
                _ventaRepository.EditVenta(detallesVenta);
                var venta = _ventaRepository.GetDetallesVenta(detallesVenta.VentaID);
                return RedirectToAction("Details", venta);
            } catch
            {
                return View(detallesVenta.VentaID);
            }
        }
        public ActionResult Delete(int ventaID)
        {
            if (!CheckSession("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            return View(ventaID);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAsync(int productoID)
        {
            int ventaID = await _ventaRepository.GetVentaID(Global.user.UsuarioID);
            try
            {
                await _ventaRepository.RmVenta(productoID, Global.user.UsuarioID);
                return RedirectToAction("Index");
            } catch{
                return RedirectToAction("Details", ventaID);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddVenta(int productID)
        {
            int userID = Global.user.UsuarioID;
            await _ventaRepository.AddVenta(productID, userID);
            return RedirectToAction("Index");
        }
        protected bool CheckSession(string key)
        {
            return HttpContext.Session.Keys.Contains(key);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Amazon</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Amazon.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Amazon</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (Global.user != null && Global.IsAdmin)
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                        </li>
                        }
                        @if (Global.user != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Carrito" asp-action="Index">Carrito</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Venta" asp-action="Index">Ventas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Logout">Logout</a>
                            </li>
                            <li class="nav-item">
                                <p class="nav-link text-dark mb-0">Carrito: @Global.carritoCantidad</p>
                            </li>   
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Amazon - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>